# Generated by Django 4.2.7 on 2026-03-13 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Batches",
                "db_table": "batch",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "domain",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="mcqs.domain",
                    ),
                ),
            ],
            options={
                "db_table": "topic",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Subtopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtopics",
                        to="mcqs.topic",
                    ),
                ),
            ],
            options={
                "db_table": "subtopic",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MCQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "Easy"),
                            ("Medium", "Medium"),
                            ("Hard", "Hard"),
                        ],
                        default="Medium",
                        max_length=10,
                    ),
                ),
                ("tag", models.CharField(blank=True, max_length=100)),
                ("question_text", models.TextField()),
                ("option_a", models.TextField()),
                ("option_b", models.TextField()),
                ("option_c", models.TextField()),
                ("option_d", models.TextField()),
                (
                    "correct_answer",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                    ),
                ),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mcqs",
                        to="mcqs.batch",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcqs",
                        to="mcqs.domain",
                    ),
                ),
                (
                    "subtopic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcqs",
                        to="mcqs.subtopic",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcqs",
                        to="mcqs.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "MCQ",
                "verbose_name_plural": "MCQs",
                "db_table": "mcq",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="domain",
            index=models.Index(fields=["name"], name="domain_name_82b1c3_idx"),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["domain", "name"], name="topic_domain__ede400_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="topic",
            unique_together={("domain", "name")},
        ),
        migrations.AddIndex(
            model_name="subtopic",
            index=models.Index(
                fields=["topic", "name"], name="subtopic_topic_i_49b18b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subtopic",
            unique_together={("topic", "name")},
        ),
        migrations.AddIndex(
            model_name="mcq",
            index=models.Index(
                fields=["domain", "topic", "subtopic"], name="mcq_domain__b8751c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mcq",
            index=models.Index(fields=["difficulty"], name="mcq_difficu_e94744_idx"),
        ),
        migrations.AddIndex(
            model_name="mcq",
            index=models.Index(fields=["tag"], name="mcq_tag_22ae68_idx"),
        ),
        migrations.AddIndex(
            model_name="mcq",
            index=models.Index(fields=["batch"], name="mcq_batch_i_1c5bc3_idx"),
        ),
    ]
