# Generated by Django 4.2.7 on 2026-03-14 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mcqs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="domain",
            options={"ordering": ["display_order", "name"]},
        ),
        migrations.AlterModelOptions(
            name="mcq",
            options={
                "ordering": ["domain__name", "topic__name", "subtopic__name", "id"],
                "verbose_name": "MCQ",
                "verbose_name_plural": "MCQs",
            },
        ),
        migrations.AddField(
            model_name="domain",
            name="display_order",
            field=models.IntegerField(
                default=0, help_text="Order in which domain should be displayed"
            ),
        ),
        migrations.AddIndex(
            model_name="domain",
            index=models.Index(
                fields=["display_order"], name="domain_display_487f0d_idx"
            ),
        ),
    ]
